In [228]:
import pandas as pd
import numpy as np
import string

In [102]:
referee_list = pd.DataFrame(columns = ["referee"])
for year in range(2014,2019):
    referee = pd.read_csv("./" + str(year) + "/" + str(year) + "_match-list.csv").referee
    referee_list = referee_list.append(pd.DataFrame(referee, columns = ["referee"]))

In [50]:
def strip_accents(string):
    ans = string
    replacements = {
        "ç": "c",
        "é": "e",
        "'": " "
    }
    for el in replacements.keys():
        ans = ans.replace(el, replacements[el])
    return ans

In [ ]:
referee_list.referee = referee_list.referee.str.lower().str.strip().apply(strip_accents).str.replace(" ", "_")

In [104]:
referee_list = referee_list.drop_duplicates()

In [105]:
referees = pd.DataFrame({"referee_name": referee_list.referee, "referee_id": range(1, referee_list.shape[0]+1)})

In [106]:
referees.to_csv("referees.csv", index=False)

In [85]:
team_list = pd.DataFrame(columns = ["team_name_3"])
for year in range(2014,2019):
    filename = "./" + str(year) + "/" + str(year) + "_match-list.csv"
    match_list = pd.read_csv(filename)
    match_list.team_home = match_list.team_home.str.replace("Atletico - PR", "Atlético - PR")
    match_list.team_away = match_list.team_away.str.replace("Atletico - PR", "Atlético - PR")
    match_list.to_csv(filename, index=False)

In [86]:
team_list = pd.DataFrame(columns = ["team_name_3"])
for year in range(2014,2019):
    filename = "./" + str(year) + "/" + str(year) + "_match-list.csv"
    match_list = pd.read_csv(filename)
    team_list = team_list.append(pd.DataFrame({"team_name_3": match_list.team_home}))
    team_list = team_list.append(pd.DataFrame({"team_name_3": match_list.team_away}))

In [87]:
team_list.drop_duplicates().sort_values("team_name_3").head(100)

           team_name_3
8         América - MG
18       Atlético - GO
5        Atlético - MG
4        Atlético - PR
9            Avaí - SC
6           Bahia - BA
10       Botafogo - RJ
16          Ceará - CE
9     Chapecoense - SC
12    Corinthians - SP
14       Coritiba - PR
8        Criciuma - SC
15       Cruzeiro - MG
18    Figueirense - SC
0        Flamengo - RJ
1      Fluminense - RJ
19          Goiás - GO
17         Grêmio - RS
7   Internacional - RS
16      Joinville - SC
13      Palmeiras - SP
11         Paraná - PR
17    Ponte Preta - SP
5      Santa Cruz - PE
3          Santos - SP
11          Sport - PE
2       São Paulo - SP
7   Vasco da Gama - RJ
16        Vitória - BA